dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

# dependencies:
#   - smartcontractkit/chainlink-brownie-contracts@0.3.0
#   - OpenZeppelin/openzeppelin-contracts@3.4.0

# compiler:
#   solc:
#     remappings:
#     - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'
#     - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'

networks:
  default: development
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
  mainnet-fork:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'